import random
def value_Checker():
    random_int=random.randint(1, 100)
    user_number=int(input("GUESS THE NUMBER GENERATED BY COMPUTER"))
    if user_number==random_int:
        return 1
    else:
        print("\t\t THE VALUE GENERATED BY COMPUTER IS ",random_int)
        return 0
print("\t\t\t\t GUESS THE NUMBER GAME")
while True:
    print("HELLO USER! ")
    print("\t YOU WILL HAVE 3 ATTEMPTS TO GUESS THE NUMBER GENERATED BY THE COMPUTER")
    print("\t NO.OF.ATTEMPTS YOU WIN WILL DECIDE THE GAME")
    user_Attempts=0
    computer_Attempts=0
    for i in range(1,4):
        if value_Checker()==1 :
            user_Attempts+=1
        else:
            computer_Attempts+=1
    print("YOU HAVE WON,",user_Attempts,"NO.OF.ATTEMPTS OUT OF 3 ATTEMPTS")
    print("COMPUTER HAVE WON,",computer_Attempts,"NO.OF ATTEMPTS OUT OF 3 ATTEMPTS")
    res="YOU HAVE WON THE GAME" if computer_Attempts<user_Attempts else "COMPUTER WINS THE GAME"
    print(res)
    replay=input("DO YOU WANT TO PLAY AGAIN(YES/NO):")
    if replay in('no','No','NO'):
        print("\t\t\t\tTHANK YOU")
        break
        
