import random
print("GUESS THE NUMBER GAME")
loop_Variable=0
def value_Checker():
    random_int=random.randint(1, 100)
    user_number=int(input("GUESS THE NUMBER GENERATED BY COMPUTER"))
    if user_number==random_int:
        print("\t\t YOU WON THE GAME")
    else:
        print("\t\t SORRY,COMPUTER WON THE GAME")
        print("\t\t THE VALUE GENERATED BY COMPUTER IS ",random_int)
value_Checker()
while loop_Variable==0:
    wish=input("DO YOU WANT TO CONTINUE THE GAME")
    if wish in ('yes','YES'):
        value_Checker()
    else:
        loop_Variable=1    
